### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by baptistebriel** [AriaMinaei/Griddify#2]
Could there be any Retina support on this plugin?
Nice work, thanks!

![capture decran 2014-05-21 a 10 42 02](https://cloud.githubusercontent.com/assets/2464663/3037728/d1a52a84-e0c3-11e3-8bd0-74a7a13feee1.png)

**Comment by AriaMinaei** [comment]
Closing, since HTML panels seem to be retina-ready on CC 2014+.
