### ISSUE TITLE
Can't find CEP folder in CC2015 and can't install by extension manager!

### ISSUE THREAD

**Issue by saintz1** [AriaMinaei/Griddify#29]
Hi Griddify, 

I'm alright with working with it in CS6 but when I change to CC2015, I can't find the folder to install manually or automatically by extension manager.

Can you guide me through the process of installing in CC2015 or is it possible to or not?

**Comment by OscarBarrett** [comment]
I've submitted a PR (#30) as CC 2015 requires some updates to the manifest file.
Take a look at the updates to the manifest file and manual installation instructions.

**Comment by achiandet** [comment]
Just upgraded to CC 2015, this is a bummer that it's still not fixed.

**Comment by AriaMinaei** [comment]
Sorry for the delay guys. I've pushed a [new version](http://gelobi.org/griddify). The installation instructions are also updated. Please take a look and let me know if it solves the problem.

**Comment by achiandet** [comment]
Thanks!  Worked flawlesslyy with ZXP.

**Comment by AriaMinaei** [comment]
Great! Thanks @achiandet!
